[project]
name = "iina-plugin-starter-template-tests"
version = "0.2.0a2"
requires-python = ">=3.13"
dependencies = ["copier==9.18.2", "pytest==8.4.2", "PyYAML==6.0.2"]
[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
addopts = "-ra"
[tool.ruff]
line-length = 100
target-version = "py313"
exclude = ["template", "history"]
