"""Offline fixture renderer for Jinja/path tests ONLY. This is NOT Copier.

It does not implement Git lineage, patch merging, trust checks or Copier's complete
question semantics. Production generation and upgrade evidence require test_real_copier.
"""
from __future__ import annotations
import json,re,shutil
from pathlib import Path
from types import SimpleNamespace
import jinja2,yaml
ROOT=Path(__file__).resolve().parents[1]
PRESETS=('command','sidebar','overlay','controller')
DEFAULTS=dict(plugin_name='IINA Example',plugin_slug='iina-example',plugin_identifier='org.example.iina-example',description='A typed IINA plugin.',user_name='Plugin Author',preset='command',preferences=False,docs_profile='markdown',hooks=False)

def environment() -> jinja2.Environment:
    config=yaml.safe_load((ROOT/'copier.yml').read_text())
    envops=config['_envops'].copy();envops['undefined']=jinja2.StrictUndefined
    env=jinja2.Environment(**envops)
    env.filters['regex_search']=lambda value,pattern:re.search(pattern,value)
    env.filters['to_nice_yaml']=lambda value:yaml.safe_dump(value,sort_keys=True,allow_unicode=True).rstrip()
    return env

def render(destination: Path, answers: dict[str, object] | None=None) -> list[str]:
    if destination.exists():raise ValueError('Fixture destination must be absent')
    data={**DEFAULTS,**(answers or {})}
    if data['preset'] not in PRESETS:raise ValueError('Invalid preset')
    if not isinstance(data['preferences'],bool) or not isinstance(data['hooks'],bool):raise ValueError('Expected a boolean')
    if data['docs_profile'] not in ('markdown','starlight'):raise ValueError('Invalid docs profile')
    config=yaml.safe_load((ROOT/'copier.yml').read_text());env=environment()
    context={**data,'_copier_operation':'copy','_copier_conf':SimpleNamespace(answers_file='.copier-answers.yml'),
             '_copier_answers':{'_src_path':'FIXTURE-NOT-COPIER','_commit':'FIXTURE',**data}}
    for key,definition in config.items():
        if not key.startswith('_') and 'validator' in definition:
            message=env.from_string(definition['validator']).render(context).strip()
            if message:raise ValueError(f'{key}: {message}')
    files=[]
    for source in sorted((ROOT/'template').rglob('*')):
        if not source.is_file():continue
        if any(p in {'__pycache__','.pytest_cache','.DS_Store'} for p in source.parts) or source.suffix=='.pyc':continue
        parts=[]
        for part in source.relative_to(ROOT/'template').parts:
            rendered=env.from_string(part.removesuffix('.jinja')).render(context)
            if not rendered:break
            if rendered in ('.','..') or '/' in rendered or '\\' in rendered:raise ValueError('Unsafe rendered component')
            parts.append(rendered)
        else:
            path=destination.joinpath(*parts);path.parent.mkdir(parents=True,exist_ok=True)
            contents=source.read_text()
            if source.name.endswith('.jinja'):contents=env.from_string(contents).render(context)
            path.write_text(contents);files.append(path.relative_to(destination).as_posix())
    return files

if __name__=='__main__':
    import argparse
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('destination',type=Path);parser.add_argument('--preset',choices=PRESETS,default='command')
    parser.add_argument('--preferences',action='store_true')
    args=parser.parse_args();render(args.destination,{'preset':args.preset,'preferences':args.preferences})
    print('Fixture rendered. NOT generated by Copier; do not use its answers for updates.')
